apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ks1elit23-go 
  janus-idp.io/tekton: ks1elit23-go
  backstage.io/kubernetes-id: ks1elit23-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ks1elit23-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  