apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ks1elit23-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ks1elit23-go 
  name: ks1elit23-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ks1elit23-go
    weight: 100 
